os: Visual Studio 2017

cache: c:\users\appveyor\clcache

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" .. -DARCH=default -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild TurtleCoin.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir BlogCoin-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe BlogCoin-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE turtlecoin-%APPVEYOR_REPO_TAG_NAME%
  - 7z a BlogCoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip BlogCoin-%APPVEYOR_REPO_TAG_NAME%
  - copy BlogCoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: BlogCoin-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: BlogCoinRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: +PIlctTY6QsXh2gdWquW4i7Cc1Fkqg84ZOS8yunncBYRZr6660aEnNqTniHR3QSM
    artifact: BlogCoinRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: blognetwork/blogcoin
      appveyor_repo_tag: true
