sudo: false
language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # OSX, clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

install:
# Need to uninstall oclint to get newer gcc installed https://github.com/travis-ci/travis-ci/issues/8826
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true ; fi

# Need a newer version of llvm to link against to get std::filesystem / std::experimental::filesystem
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry brew upgrade llvm ; fi

# Need to make sure that we have openssl installed
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry brew upgrade openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl /usr/local/include ; fi

# Neeed to install ccache
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="BlogCoinDaemon blogcoin-miner BlogCoinWallet blogcoin-service BlogCoinWallet++ cryptotest wallet-api"
- ${STRIP} ${TARGETS}
- rm -rf BlogCoin-${TRAVIS_TAG}
- mkdir BlogCoin-${TRAVIS_TAG}
- cp ${TARGETS} BlogCoin-${TRAVIS_TAG}/
- cp ../../LICENSE BlogCoin-${TRAVIS_TAG}/
- tar cvfz BlogCoin-${TRAVIS_TAG}-${LABEL}.tar.gz BlogCoin-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp BlogCoin-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: iMIRE+iGreWGvMUyCdUWktvKKjkfaT55wKBY5kHj/xCUb/VDVImAa/3ldR2P+nPMN5MB4R+mWmY0oor6+30JTQlRofEV8NknHP9FLDGG2+DfVCoJ7Gh+15GtWKbsRbCBIFw5092PgI9en18ArLoDVcOGx0+uF3knwgnJKDynsI3FNkxr+D+gMrKhoZ5iZ7TDBBLax5RVjz36uSIdrzQyHns0bWUaK5p0dlovM0+Voo/XQXgppB30OCtzEexefY/GKEGnacMsJcnJs3tWbetbTVGtJ875l5O+9azQQtPOUDXyO6NBWhiYzOa29LCn3iIayHJzgfxcoReuYi8YW0yF+1ySuKHAEb8gzMjrlIGxVlvuckagyisj/clIl62WkezLB8VOgnERUgdqFsCcKej67X8pGCpchMSwApyYUrq17dLfR2f1rC56SkEUna9lmlRKusMe6K/nGHKTQ2jytgoMjDhOuqAIP0dY/An0o2Rh3j0gCqgaWjl1CrlU3ppJFdZeQdDhSQ+1q7Akrx3EL/vxLKpO1hCV1z5c6ZVc1P2XUMQmyOqZEkRzNWhMBFpAUeFax1yOy5bw7DbQlR+BV6jF5qmKNPCB1nJqDgqw/bV1ws++s2tuX/51OwpThBV7dWDlFC8PID6SnHWPHDW9jv+JhY0ePsFoogsKRcPkDXQp4iY=
    file:
      - BlogCoin-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    on:
      repo: blognetwork/blogcoin
      tags: true
      condition: "$_DEPLOYABLE = true"
